import Head from 'next/head';
import Link from 'next/link';
import styles from './Blocks/Blocks.module.css'

const Layout = ({ children, title = 'Block Chain' }) => {
  return (
    <div className='layout'>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='header'>
        <Link href='/' passHref>
          <a>
            <h1 className={styles.chain}>Latest Blocks</h1>
          </a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  );
};

export default Layout;